name: bebop_dart
description: The Dart runtime for Bebop, a schema-based serialization format.
version: 0.1.0
homepage: https://github.com/RainwayApp/bebop_dart

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
