[package]
name = "manual-testing"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bebop = { path = "../../../Runtime/Rust", default-features = false }
static_assertions = "1.1.0"

[features]
default = ["bebop-owned-all", "owned-generation"]
bebop-owned-all = []
owned-generation = []
