name: Bebop .NET Runtime
on:
  workflow_dispatch:
  push:
    paths:
      - "Runtime/C#/**"
  pull_request:
    paths:
      - "Runtime/C#/**"

jobs:
  build-runtime:
    env:
      TEST_ROOT: ${{github.workspace}}/Laboratory/C#/Test
      RUNTIME_ROOT: ${{github.workspace}}/Runtime/C#
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Get Enviorment Variables
        id: dotenv
        uses: falti/dotenv-action@v0.2.5

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x" # SDK Version to use; x will use the latest version of the 5.0 channel

      - name: Run Test .NET 5
        run: dotnet test -c Release -f net5.0
        working-directory: ${{env.TEST_ROOT}}

      - name: Run Test .NET Framework 4.7.2
        run: dotnet test -c Release -f net472
        working-directory: ${{env.TEST_ROOT}}

      - name: Run Test .NET Framework 4.8
        run: dotnet test -c Release -f net48
        working-directory: ${{env.TEST_ROOT}}

      - name: Restore Project
        run: dotnet restore
        working-directory: ${{env.RUNTIME_ROOT}}

      - name: Build Runtime
        run: dotnet build -c Release -p:ReleaseVersion=${{ steps.dotenv.outputs.version }}
        working-directory: ${{env.RUNTIME_ROOT}}

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: bebop-runtime-cs-latest
          path: ${{env.RUNTIME_ROOT}}/bin/Release/*.nupkg
