name: Bebop WebAssembly REPL
on:
  workflow_dispatch:
  push:
    paths:
      - "Repl/**"
  pull_request:
    paths:
      - "Repl/**"
jobs:
  build-repl:
    env:
      REPL_ROOT: ${{github.workspace}}/Repl
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Get Enviorment Variables
        id: dotenv
        uses: falti/dotenv-action@v0.2.5

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x" # SDK Version to use; x will use the latest version of the 6.0 channel
      - name: Restore Project
        run: dotnet restore
        working-directory: ${{env.REPL_ROOT}}
      - name: Build REPL
        run: dotnet publish -c Release -p:ReleaseVersion=${{ steps.dotenv.outputs.version }}
        working-directory: ${{env.REPL_ROOT}}

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: bebop-repl-latest
          path: ${{github.workspace}}/bin/repl/Release/publish/wwwroot/
