name: Test TypeScript
on:
  push:
    branches:
      - master
      - test-action-new-cli
  pull_request:
jobs:
  test-typescript:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "18.16.0" # LTS
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: 'preview'
      - name: Build Typescript runtime
        run: |
          yarn install
          yarn test
          yarn build
        working-directory: ./Runtime/TypeScript
      - name: Build and run tests
        run: |
          yarn install
          bash compile-schemas.sh
          yarn test
        working-directory: ./Laboratory/TypeScript
